# Generated by Django 4.2.6 on 2023-10-29 05:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=250)),
                ('description', models.TextField(default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('prod_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('append_date', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(default=None, null=True, upload_to='media/')),
            ],
            options={
                'ordering': ['prod_name'],
                'indexes': [models.Index(fields=['prod_name'], name='app_product_prod_na_cf3a70_idx'), models.Index(fields=['-append_date'], name='app_product_append__f1c6e2_idx'), models.Index(fields=['price'], name='app_product_price_d352a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='app.OrderProducts', to='app.product'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_name'], name='app_client_client__83b5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-reg_date'], name='app_client_reg_dat_f86b75_idx'),
        ),
    ]
